# Generated by Django 5.2.17 on 2026-09-21 15:11

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Ota kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['parent_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Eski narx')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='products/covers/', verbose_name='Asosiy rasm')),
                ('material', models.CharField(choices=[('beech', "Buk yog'ochi"), ('oak', "Eman yog'ochi"), ('walnut', "Yong'oq yog'ochi"), ('mdf', 'MDF / LDSP'), ('linen', "Zig'ir mato"), ('velour', 'Velur'), ('boucle', 'Bukle mato'), ('rattan', 'Ratan')], max_length=30, verbose_name='Material')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Eni (sm)')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='Chuqurligi (sm)')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Balandligi (sm)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('status', models.CharField(choices=[('in_stock', 'Mavjud'), ('on_order', 'Buyurtmaga')], default='in_stock', max_length=10, verbose_name='Holat')),
                ('popularity', models.PositiveIntegerField(default=0, verbose_name='Ommaboplik')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('is_new', models.BooleanField(default=False, verbose_name='Yangi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
            bases=(core.utils.WebPMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Rasm')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt matn')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
                'ordering': ['sort_order'],
            },
            bases=(core.utils.WebPMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('color_code', models.CharField(default='#000000', max_length=7, verbose_name='Rang kodi (HEX)')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Narx farqi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='catalog_pro_categor_da0f0a_idx'),
        ),
    ]
