# Generated by Django 5.2.17 on 2026-09-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id'], 'verbose_name': 'Variant', 'verbose_name_plural': 'Variantlar'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nomi (ru)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (ru)'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_label',
            field=models.CharField(blank=True, help_text="Masalan: Buk yog'ochi, zig'ir mato", max_length=200, verbose_name='Material izohi'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_label_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Material izohi (ru)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (ru)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_ru',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nomi (ru)'),
        ),
    ]
