# Generated by Django 5.2.17 on 2026-09-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='F.I.Sh.')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('processing', 'Jarayonda'), ('delivered', 'Yetkazilgan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=12, verbose_name='Holat')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('online', 'Payme / Click'), ('terminal', 'Terminal')], default='cash', max_length=10, verbose_name="To'lov usuli")),
                ('payment_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarilgan')], default='pending', max_length=10, verbose_name="To'lov holati")),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi (snapshot)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx (snapshot)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma pozitsiyasi',
                'verbose_name_plural': 'Buyurtma pozitsiyalari',
            },
        ),
    ]
