# Generated by Django 5.2.17 on 2026-09-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('is_processed', models.BooleanField(default=False, verbose_name="Ko'rib chiqildi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
